version: '3'
services:
  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: 'mySuperSecretKeyKey12345'
      SECRET: 'mySuperSecretSecretKey12345'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: '111111'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: './database/data.db'
      WEBSOCKETS_ENABLED: true
